### ISSUE TITLE
Unknown column 'relationships.personObjectId' in 'field list'

### ISSUE THREAD

**Issue by vanshady** [vanshady/crunchbase_analysis#2]
After correct configuration according to `README.md` , running `npm test` would lead to this error.
```
Connection has been established successfully.
Nick Wilder
Unhandled rejection SequelizeDatabaseError: ER_BAD_FIELD_ERROR: Unknown column 'relationships.personObjectId' in 'field list'
    at [object Object].Query.formatError (/Users/vanshady/Code/crunchbase_analysis/graphql-server/node_modules/sequelize/lib/dialects/mysql/query.js:175:14)
    at Query._callback (/Users/vanshady/Code/crunchbase_analysis/graphql-server/node_modules/sequelize/lib/dialects/mysql/query.js:49:21)
    at Query.Sequence.end (/Users/vanshady/Code/crunchbase_analysis/graphql-server/node_modules/mysql/lib/protocol/sequences/Sequence.js:96:24)
    at Query.ErrorPacket (/Users/vanshady/Code/crunchbase_analysis/graphql-server/node_modules/mysql/lib/protocol/sequences/Query.js:94:8)
    at Protocol._parsePacket (/Users/vanshady/Code/crunchbase_analysis/graphql-server/node_modules/mysql/lib/protocol/Protocol.js:280:23)
    at Parser.write (/Users/vanshady/Code/crunchbase_analysis/graphql-server/node_modules/mysql/lib/protocol/Parser.js:73:12)
    at Protocol.write (/Users/vanshady/Code/crunchbase_analysis/graphql-server/node_modules/mysql/lib/protocol/Protocol.js:39:16)
    at Socket.<anonymous> (/Users/vanshady/Code/crunchbase_analysis/graphql-server/node_modules/mysql/lib/Connection.js:96:28)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:146:16)
    at Socket.Readable.push (_stream_readable.js:110:10)
    at TCP.onread (net.js:523:20)
```

**Comment by vanshady** [comment]
The SQL generated is as below 
```

Executing (default): SELECT 1+1 AS result
Executing (default): SELECT `degrees`.`id`, `degrees`.`object_id`, `degrees`.`degree_type`, `degrees`.`subject`, `degrees`.`institution`, `degrees`.`graduated_at`, `degrees`.`created_at`, `degrees`.`updated_at`, `people`.`id` AS `people.id`, `people`.`object_id` AS `people.object_id`, `people`.`first_name` AS `people.first_name`, `people`.`last_name` AS `people.last_name`, `people`.`birthplace` AS `people.birthplace`, `people`.`affiliation_name` AS `people.affiliation_name` FROM `cb_degrees` AS `degrees` LEFT OUTER JOIN `cb_people` AS `people` ON `degrees`.`object_id` = `people`.`object_id` WHERE `degrees`.`object_id` = 'p:3262' LIMIT 1;
Executing (default): SELECT `people`.`id`, `people`.`object_id`, `people`.`first_name`, `people`.`last_name`, `people`.`birthplace`, `people`.`affiliation_name`, `degrees`.`id` AS `degrees.id`, `degrees`.`object_id` AS `degrees.object_id`, `degrees`.`degree_type` AS `degrees.degree_type`, `degrees`.`subject` AS `degrees.subject`, `degrees`.`institution` AS `degrees.institution`, `degrees`.`graduated_at` AS `degrees.graduated_at`, `degrees`.`created_at` AS `degrees.created_at`, `degrees`.`updated_at` AS `degrees.updated_at`, `relationships`.`id` AS `relationships.id`, `relationships`.`relationship_id` AS `relationships.relationship_id`, `relationships`.`person_object_id` AS `relationships.person_object_id`, `relationships`.`relationship_object_id` AS `relationships.relationship_object_id`, `relationships`.`start_at` AS `relationships.start_at`, `relationships`.`end_at` AS `relationships.end_at`, `relationships`.`is_past` AS `relationships.is_past`, `relationships`.`sequence` AS `relationships.sequence`, `relationships`.`title` AS `relationships.title`, `relationships`.`created_at` AS `relationships.created_at`, `relationships`.`updated_at` AS `relationships.updated_at`, `relationships`.`personObjectId` AS `relationships.personObjectId` FROM `cb_people` AS `people` LEFT OUTER JOIN `cb_degrees` AS `degrees` ON `people`.`object_id` = `degrees`.`object_id` LEFT OUTER JOIN `cb_relationships` AS `relationships` ON `people`.`object_id` = `relationships`.`person_object_id` WHERE `people`.`object_id` = 'p:3262';
Executing (default): SELECT `relationships`.`id`, `relationships`.`relationship_id`, `relationships`.`person_object_id`, `relationships`.`relationship_object_id`, `relationships`.`start_at`, `relationships`.`end_at`, `relationships`.`is_past`, `relationships`.`sequence`, `relationships`.`title`, `relationships`.`created_at`, `relationships`.`updated_at`, `relationships`.`personObjectId`, `people`.`id` AS `people.id`, `people`.`object_id` AS `people.object_id`, `people`.`first_name` AS `people.first_name`, `people`.`last_name` AS `people.last_name`, `people`.`birthplace` AS `people.birthplace`, `people`.`affiliation_name` AS `people.affiliation_name`, `object`.`id` AS `object.id`, `object`.`entity_type` AS `object.entity_type`, `object`.`entity_id` AS `object.entity_id`, `object`.`parent_id` AS `object.parent_id`, `object`.`name` AS `object.name`, `object`.`normalized_name` AS `object.normalized_name`, `object`.`permalink` AS `object.permalink`, `object`.`category_code` AS `object.category_code`, `object`.`status` AS `object.status`, `object`.`founded_at` AS `object.founded_at`, `object`.`closed_at` AS `object.closed_at`, `object`.`domain` AS `object.domain`, `object`.`homepage_url` AS `object.homepage_url`, `object`.`twitter_username` AS `object.twitter_username`, `object`.`logo_url` AS `object.logo_url`, `object`.`logo_width` AS `object.logo_width`, `object`.`logo_height` AS `object.logo_height`, `object`.`short_description` AS `object.short_description`, `object`.`description` AS `object.description`, `object`.`overview` AS `object.overview`, `object`.`tag_list` AS `object.tag_list`, `object`.`country_code` AS `object.country_code`, `object`.`state_code` AS `object.state_code`, `object`.`city` AS `object.city`, `object`.`region` AS `object.region`, `object`.`first_investment_at` AS `object.first_investment_at`, `object`.`last_investment_at` AS `object.last_investment_at`, `object`.`investment_rounds` AS `object.investment_rounds`, `object`.`invested_companies` AS `object.invested_companies`, `object`.`first_funding_at` AS `object.first_funding_at`, `object`.`last_funding_at` AS `object.last_funding_at`, `object`.`funding_rounds` AS `object.funding_rounds`, `object`.`funding_total_usd` AS `object.funding_total_usd`, `object`.`first_milestone_at` AS `object.first_milestone_at`, `object`.`last_milestone_at` AS `object.last_milestone_at`, `object`.`milestones` AS `object.milestones`, `object`.`relationships` AS `object.relationships`, `object`.`created_by` AS `object.created_by`, `object`.`created_at` AS `object.created_at`, `object`.`updated_at` AS `object.updated_at` FROM `cb_relationships` AS `relationships` LEFT OUTER JOIN `cb_people` AS `people` ON `relationships`.`person_object_id` = `people`.`object_id` LEFT OUTER JOIN `cb_objects` AS `object` ON `relationships`.`relationship_object_id` = `object`.`id` WHERE `relationships`.`person_object_id` = 'p:3262';
Executing (default): SELECT `objects`.`id`, `objects`.`entity_type`, `objects`.`entity_id`, `objects`.`parent_id`, `objects`.`name`, `objects`.`normalized_name`, `objects`.`permalink`, `objects`.`category_code`, `objects`.`status`, `objects`.`founded_at`, `objects`.`closed_at`, `objects`.`domain`, `objects`.`homepage_url`, `objects`.`twitter_username`, `objects`.`logo_url`, `objects`.`logo_width`, `objects`.`logo_height`, `objects`.`short_description`, `objects`.`description`, `objects`.`overview`, `objects`.`tag_list`, `objects`.`country_code`, `objects`.`state_code`, `objects`.`city`, `objects`.`region`, `objects`.`first_investment_at`, `objects`.`last_investment_at`, `objects`.`investment_rounds`, `objects`.`invested_companies`, `objects`.`first_funding_at`, `objects`.`last_funding_at`, `objects`.`funding_rounds`, `objects`.`funding_total_usd`, `objects`.`first_milestone_at`, `objects`.`last_milestone_at`, `objects`.`milestones`, `objects`.`relationships`, `objects`.`created_by`, `objects`.`created_at`, `objects`.`updated_at`, `relationship`.`id` AS `relationship.id`, `relationship`.`relationship_id` AS `relationship.relationship_id`, `relationship`.`person_object_id` AS `relationship.person_object_id`, `relationship`.`relationship_object_id` AS `relationship.relationship_object_id`, `relationship`.`start_at` AS `relationship.start_at`, `relationship`.`end_at` AS `relationship.end_at`, `relationship`.`is_past` AS `relationship.is_past`, `relationship`.`sequence` AS `relationship.sequence`, `relationship`.`title` AS `relationship.title`, `relationship`.`created_at` AS `relationship.created_at`, `relationship`.`updated_at` AS `relationship.updated_at`, `relationship`.`personObjectId` AS `relationship.personObjectId`, `office`.`id` AS `office.id`, `office`.`object_id` AS `office.object_id`, `office`.`office_id` AS `office.office_id`, `office`.`description` AS `office.description`, `office`.`region` AS `office.region`, `office`.`address1` AS `office.address1`, `office`.`address2` AS `office.address2`, `office`.`city` AS `office.city`, `office`.`zip_code` AS `office.zip_code`, `office`.`state_code` AS `office.state_code`, `office`.`country_code` AS `office.country_code`, `office`.`latitude` AS `office.latitude`, `office`.`longitude` AS `office.longitude`, `office`.`created_at` AS `office.created_at`, `office`.`updated_at` AS `office.updated_at`, `acquiredBy`.`id` AS `acquiredBy.id`, `acquiredBy`.`entity_type` AS `acquiredBy.entity_type`, `acquiredBy`.`entity_id` AS `acquiredBy.entity_id`, `acquiredBy`.`parent_id` AS `acquiredBy.parent_id`, `acquiredBy`.`name` AS `acquiredBy.name`, `acquiredBy`.`normalized_name` AS `acquiredBy.normalized_name`, `acquiredBy`.`permalink` AS `acquiredBy.permalink`, `acquiredBy`.`category_code` AS `acquiredBy.category_code`, `acquiredBy`.`status` AS `acquiredBy.status`, `acquiredBy`.`founded_at` AS `acquiredBy.founded_at`, `acquiredBy`.`closed_at` AS `acquiredBy.closed_at`, `acquiredBy`.`domain` AS `acquiredBy.domain`, `acquiredBy`.`homepage_url` AS `acquiredBy.homepage_url`, `acquiredBy`.`twitter_username` AS `acquiredBy.twitter_username`, `acquiredBy`.`logo_url` AS `acquiredBy.logo_url`, `acquiredBy`.`logo_width` AS `acquiredBy.logo_width`, `acquiredBy`.`logo_height` AS `acquiredBy.logo_height`, `acquiredBy`.`short_description` AS `acquiredBy.short_description`, `acquiredBy`.`description` AS `acquiredBy.description`, `acquiredBy`.`overview` AS `acquiredBy.overview`, `acquiredBy`.`tag_list` AS `acquiredBy.tag_list`, `acquiredBy`.`country_code` AS `acquiredBy.country_code`, `acquiredBy`.`state_code` AS `acquiredBy.state_code`, `acquiredBy`.`city` AS `acquiredBy.city`, `acquiredBy`.`region` AS `acquiredBy.region`, `acquiredBy`.`first_investment_at` AS `acquiredBy.first_investment_at`, `acquiredBy`.`last_investment_at` AS `acquiredBy.last_investment_at`, `acquiredBy`.`investment_rounds` AS `acquiredBy.investment_rounds`, `acquiredBy`.`invested_companies` AS `acquiredBy.invested_companies`, `acquiredBy`.`first_funding_at` AS `acquiredBy.first_funding_at`, `acquiredBy`.`last_funding_at` AS `acquiredBy.last_funding_at`, `acquiredBy`.`funding_rounds` AS `acquiredBy.funding_rounds`, `acquiredBy`.`funding_total_usd` AS `acquiredBy.funding_total_usd`, `acquiredBy`.`first_milestone_at` AS `acquiredBy.first_milestone_at`, `acquiredBy`.`last_milestone_at` AS `acquiredBy.last_milestone_at`, `acquiredBy`.`milestones` AS `acquiredBy.milestones`, `acquiredBy`.`relationships` AS `acquiredBy.relationships`, `acquiredBy`.`created_by` AS `acquiredBy.created_by`, `acquiredBy`.`created_at` AS `acquiredBy.created_at`, `acquiredBy`.`updated_at` AS `acquiredBy.updated_at`, `acquiredBy.cb_acquisitions`.`id` AS `acquiredBy.cb_acquisitions.id`, `acquiredBy.cb_acquisitions`.`acquisition_id` AS `acquiredBy.cb_acquisitions.acquisition_id`, `acquiredBy.cb_acquisitions`.`acquiring_object_id` AS `acquiredBy.cb_acquisitions.acquiring_object_id`, `acquiredBy.cb_acquisitions`.`acquired_object_id` AS `acquiredBy.cb_acquisitions.acquired_object_id`, `acquiredBy.cb_acquisitions`.`term_code` AS `acquiredBy.cb_acquisitions.term_code`, `acquiredBy.cb_acquisitions`.`price_amount` AS `acquiredBy.cb_acquisitions.price_amount`, `acquiredBy.cb_acquisitions`.`price_currency_code` AS `acquiredBy.cb_acquisitions.price_currency_code`, `acquiredBy.cb_acquisitions`.`acquired_at` AS `acquiredBy.cb_acquisitions.acquired_at`, `acquiredBy.cb_acquisitions`.`source_url` AS `acquiredBy.cb_acquisitions.source_url`, `acquiredBy.cb_acquisitions`.`source_description` AS `acquiredBy.cb_acquisitions.source_description`, `acquiredBy.cb_acquisitions`.`created_at` AS `acquiredBy.cb_acquisitions.created_at`, `acquiredBy.cb_acquisitions`.`updated_at` AS `acquiredBy.cb_acquisitions.updated_at`, `acquire`.`id` AS `acquire.id`, `acquire`.`entity_type` AS `acquire.entity_type`, `acquire`.`entity_id` AS `acquire.entity_id`, `acquire`.`parent_id` AS `acquire.parent_id`, `acquire`.`name` AS `acquire.name`, `acquire`.`normalized_name` AS `acquire.normalized_name`, `acquire`.`permalink` AS `acquire.permalink`, `acquire`.`category_code` AS `acquire.category_code`, `acquire`.`status` AS `acquire.status`, `acquire`.`founded_at` AS `acquire.founded_at`, `acquire`.`closed_at` AS `acquire.closed_at`, `acquire`.`domain` AS `acquire.domain`, `acquire`.`homepage_url` AS `acquire.homepage_url`, `acquire`.`twitter_username` AS `acquire.twitter_username`, `acquire`.`logo_url` AS `acquire.logo_url`, `acquire`.`logo_width` AS `acquire.logo_width`, `acquire`.`logo_height` AS `acquire.logo_height`, `acquire`.`short_description` AS `acquire.short_description`, `acquire`.`description` AS `acquire.description`, `acquire`.`overview` AS `acquire.overview`, `acquire`.`tag_list` AS `acquire.tag_list`, `acquire`.`country_code` AS `acquire.country_code`, `acquire`.`state_code` AS `acquire.state_code`, `acquire`.`city` AS `acquire.city`, `acquire`.`region` AS `acquire.region`, `acquire`.`first_investment_at` AS `acquire.first_investment_at`, `acquire`.`last_investment_at` AS `acquire.last_investment_at`, `acquire`.`investment_rounds` AS `acquire.investment_rounds`, `acquire`.`invested_companies` AS `acquire.invested_companies`, `acquire`.`first_funding_at` AS `acquire.first_funding_at`, `acquire`.`last_funding_at` AS `acquire.last_funding_at`, `acquire`.`funding_rounds` AS `acquire.funding_rounds`, `acquire`.`funding_total_usd` AS `acquire.funding_total_usd`, `acquire`.`first_milestone_at` AS `acquire.first_milestone_at`, `acquire`.`last_milestone_at` AS `acquire.last_milestone_at`, `acquire`.`milestones` AS `acquire.milestones`, `acquire`.`relationships` AS `acquire.relationships`, `acquire`.`created_by` AS `acquire.created_by`, `acquire`.`created_at` AS `acquire.created_at`, `acquire`.`updated_at` AS `acquire.updated_at`, `acquire.cb_acquisitions`.`id` AS `acquire.cb_acquisitions.id`, `acquire.cb_acquisitions`.`acquisition_id` AS `acquire.cb_acquisitions.acquisition_id`, `acquire.cb_acquisitions`.`acquiring_object_id` AS `acquire.cb_acquisitions.acquiring_object_id`, `acquire.cb_acquisitions`.`acquired_object_id` AS `acquire.cb_acquisitions.acquired_object_id`, `acquire.cb_acquisitions`.`term_code` AS `acquire.cb_acquisitions.term_code`, `acquire.cb_acquisitions`.`price_amount` AS `acquire.cb_acquisitions.price_amount`, `acquire.cb_acquisitions`.`price_currency_code` AS `acquire.cb_acquisitions.price_currency_code`, `acquire.cb_acquisitions`.`acquired_at` AS `acquire.cb_acquisitions.acquired_at`, `acquire.cb_acquisitions`.`source_url` AS `acquire.cb_acquisitions.source_url`, `acquire.cb_acquisitions`.`source_description` AS `acquire.cb_acquisitions.source_description`, `acquire.cb_acquisitions`.`created_at` AS `acquire.cb_acquisitions.created_at`, `acquire.cb_acquisitions`.`updated_at` AS `acquire.cb_acquisitions.updated_at`, `employee`.`id` AS `employee.id`, `employee`.`object_id` AS `employee.object_id`, `employee`.`first_name` AS `employee.first_name`, `employee`.`last_name` AS `employee.last_name`, `employee`.`birthplace` AS `employee.birthplace`, `employee`.`affiliation_name` AS `employee.affiliation_name`, `employee.relationships`.`id` AS `employee.relationships.id`, `employee.relationships`.`relationship_id` AS `employee.relationships.relationship_id`, `employee.relationships`.`person_object_id` AS `employee.relationships.person_object_id`, `employee.relationships`.`relationship_object_id` AS `employee.relationships.relationship_object_id`, `employee.relationships`.`start_at` AS `employee.relationships.start_at`, `employee.relationships`.`end_at` AS `employee.relationships.end_at`, `employee.relationships`.`is_past` AS `employee.relationships.is_past`, `employee.relationships`.`sequence` AS `employee.relationships.sequence`, `employee.relationships`.`title` AS `employee.relationships.title`, `employee.relationships`.`created_at` AS `employee.relationships.created_at`, `employee.relationships`.`updated_at` AS `employee.relationships.updated_at`, `employee.relationships`.`personObjectId` AS `employee.relationships.personObjectId` FROM `cb_objects` AS `objects` LEFT OUTER JOIN `cb_relationships` AS `relationship` ON `objects`.`id` = `relationship`.`relationship_object_id` LEFT OUTER JOIN `cb_offices` AS `office` ON `objects`.`id` = `office`.`object_id` LEFT OUTER JOIN (`cb_acquisitions` AS `acquiredBy.cb_acquisitions` INNER JOIN `cb_objects` AS `acquiredBy` ON `acquiredBy`.`id` = `acquiredBy.cb_acquisitions`.`acquiring_object_id`) ON `objects`.`id` = `acquiredBy.cb_acquisitions`.`acquired_object_id` LEFT OUTER JOIN (`cb_acquisitions` AS `acquire.cb_acquisitions` INNER JOIN `cb_objects` AS `acquire` ON `acquire`.`id` = `acquire.cb_acquisitions`.`acquired_object_id`) ON `objects`.`id` = `acquire.cb_acquisitions`.`acquiring_object_id` LEFT OUTER JOIN (`cb_relationships` AS `employee.relationships` INNER JOIN `cb_people` AS `employee` ON `employee`.`object_id` = `employee.relationships`.`personObjectId`) ON `objects`.`id` = `employee.relationships`.`relationship_object_id` WHERE `objects`.`id` = 'c:10';
```

**Comment by vanshady** [comment]
otherKey somehow doesn't work for `CBObject.Acquired` and `CBObject.Acquire`

**Comment by vanshady** [comment]
bug fixed by renaming the models
